name: supabase_isar_riverpod_playground
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  beamer: ^1.5.6
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.2
  intl: ^0.18.0
  isar: ^4.0.0-dev.10
  isar_flutter_libs: ^4.0.0-dev.10
  logger: ^2.0.1
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.0
  supabase_flutter: ^1.10.13
  toggle_switch: ^2.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icons/app-icon-1024x1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-icon-1024x1024.png"
  # command: dart run flutter_launcher_icons:main
  
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash-icon-384x384.png"
  android: true
  ios: true
  web: true
  # command: dart run flutter_native_splash:create

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/files/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svgs/
    - assets/types/
